import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <Navbar /> */}
      <body>{children}</body>
      
    </html>
  );
}
